### PR TITLE
Adding README for qwicklabs

### PR DESCRIPTION
**Pull request by homernajafi**
Adding README for qwicklabs and verify TOC

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/ok-to-test

Ok to test

**Comment by chrislovecnm** [comment]
test this please

**Comment by homernajafi** [comment]
test this please

**Comment by chrislovecnm** [comment]
test this please

**Comment by chrislovecnm** [comment]
Test this please

**Comment by homernajafi** [comment]
test this please

**Pull request merged**
