### PR TITLE
Setting K8s version to the latest

### PR DESCRIPTION
**Pull request by homernajafi**
Setting version to the latest instead of hardcoded version.

### CODE REVIEW

**Comment by homernajafi** [comment]
Tested and it's picking up the latest k8s version.

**Comment by chrislovecnm** [comment]
@homernajafi CI is failing

**Comment by chrislovecnm** [comment]
We are getting an error on the validate script.  Can you do another PR and fix that please.  Can you verify that we have a bug with validate, and if so please do another PR to fix that.

**Comment by chrislovecnm** [comment]
If you comment with a specific string CI will run automatically. Also you will need to rebase.

Thanks

**Comment by homernajafi** [comment]
Test this please

**Pull request merged**
